spring:
    application:
        name: enrollments
    kafka:
        bootstrap-servers: localhost:9092
    datasource:
        url: jdbc:mysql://localhost:3306/enrollments?useTimezone=true&serverTimezone=UTC
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: 123
    jpa:
        hibernate.ddl-auto: update

server:
    port: 0

eureka:
    instance:
        instance-id: ${spring.application.name}:${spring-cloud.application.instance_id:${random.value}}

client:
    register-with-eureka: true
    service-url:
        defaultZone: http://localhost:8761/eureka

